required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: 0
  y: 71.5
  z: 0
  yaw: -180
  pitch: 0
arenas:
  0:
    world: 'world'
    x: 0
    y: 71.5
    z: 0
    yaw: -180
    pitch: 0
  1:
    world: 'world'
    x: 155.5
    y: 69
    z: -14.5
    yaw: -180
    pitch: 0
Shelly: